In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score


nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ANIKA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
df = pd.read_csv("UpdatedResumeDataSet.csv")
df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [7]:
df.isnull().sum()

Category    0
Resume      0
dtype: int64

In [9]:
print(df.dtypes)

Category    object
Resume      object
dtype: object

In [11]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]','',text)
    tokens = text.split()
    stop_words = set(stopwords.words('english'))
    tokens=[word for word in tokens if word not in stop_words]
    cleaned_text = ' '.join(tokens)
    return cleaned_text

df['Cleaned_Resume'] = df['Resume'].apply(clean_text)
df[['Resume', 'Cleaned_Resume']].head()

,Resume,Cleaned_Resume
0,Skills * Programming Languages: Python (pandas...,skills programming languages python pandas num...
1,Education Details \r\nMay 2013 to May 2017 B.E...,education details may may uitrgpv data scienti...
2,"Areas of Interest Deep Learning, Control Syste...",areas interest deep learning control system de...
3,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,skills r python sap hana tableau sap hana sql ...
4,"Education Details \r\n MCA YMCAUST, Faridab...",education details mca ymcaust faridabad haryan...

In [13]:
print(df[['Resume', 'Cleaned_Resume']].head(10))

                                              Resume  \
0  Skills * Programming Languages: Python (pandas...
1  Education Details \r\nMay 2013 to May 2017 B.E...
2  Areas of Interest Deep Learning, Control Syste...
3  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Education Details \r\n MCA   YMCAUST,  Faridab...
5  SKILLS C Basics, IOT, Python, MATLAB, Data Sci...
6  Skills â¢ Python â¢ Tableau â¢ Data Visuali...
7  Education Details \r\n B.Tech   Rayat and Bahr...
8  Personal Skills â¢ Ability to quickly grasp t...
9  Expertise â Data and Quantitative Analysis â...

                                      Cleaned_Resume
0  skills programming languages python pandas num...
1  education details may may uitrgpv data scienti...
2  areas interest deep learning control system de...
3  skills r python sap hana tableau sap hana sql ...
4  education details mca ymcaust faridabad haryan...
5  skills c basics iot python matlab data science...
6  skills python tableau data visualization r stu...
7  education details btech rayat bahra institute ...
8  personal skills ability quickly grasp technica...
9  expertise data quantitative analysis decision ...

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
Vectorizer = TfidfVectorizer(max_features=5000)
x = Vectorizer.fit_transform(df['Cleaned_Resume'])
y = df['Category']    
print(x.shape)

(962, 5000)

In [23]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train, y_test = train_test_split(x , y , test_size = 0.2, random_state = 42)
print(x_train.shape , x_test.shape)

(769, 5000) (193, 5000)

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

model = LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')

Accuracy: 0.9948186528497409
Confusion Matrix:
[[ 3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 16
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   5]]

In [32]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy Score: {accuracy:.2f}")

Accuracy Score: 0.99

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

                           precision    recall  f1-score   support

                 Advocate       1.00      1.00      1.00         3
                     Arts       1.00      1.00      1.00         6
       Automation Testing       1.00      1.00      1.00         5
               Blockchain       1.00      1.00      1.00         7
         Business Analyst       1.00      1.00      1.00         4
           Civil Engineer       1.00      1.00      1.00         9
             Data Science       1.00      1.00      1.00         5
                 Database       1.00      1.00      1.00         8
          DevOps Engineer       1.00      0.93      0.96        14
         DotNet Developer       1.00      1.00      1.00         5
            ETL Developer       1.00      1.00      1.00         7
   Electrical Engineering       1.00      1.00      1.00         6
                       HR       1.00      1.00      1.00        12
                   Hadoop       1.00      1.00      1.00         4
       Health and fitness       1.00      1.00      1.00         7
           Java Developer       1.00      1.00      1.00        15
      Mechanical Engineer       1.00      1.00      1.00         8
Network Security Engineer       1.00      1.00      1.00         3
       Operations Manager       1.00      1.00      1.00        12
                      PMO       0.88      1.00      0.93         7
         Python Developer       1.00      1.00      1.00        10
            SAP Developer       1.00      1.00      1.00         7
                    Sales       1.00      1.00      1.00         8
                  Testing       1.00      1.00      1.00        16
            Web Designing       1.00      1.00      1.00         5

                 accuracy                           0.99       193
                macro avg       0.99      1.00      1.00       193
             weighted avg       1.00      0.99      0.99       193

In [37]:
import pickle

with open("resume_classifier_model.pkl", "wb") as f:
    pickle.dump(model, f)
    
with open("tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(Vectorizer, f)